"""Stable Harvest model identities and evidence constants."""

CONFIRMED = "CONFIRMED"
NOT_RECOVERED = "NOT_RECOVERED"

YIELD_MODEL_VERSION = "harvest-estimated-yield-per-node/v1-native-static-profile"
YIELD_SCORE_BASIS = "ESTIMATED_RESOURCE_UNITS_PER_COMPLETE_NODE"
STATIC_COMPLETE_NODE_SCORE_BASIS = "STATIC_COMPLETE_NODE_TARGET_RESOURCE_UNITS"
NORMALIZED_HARVEST_AMOUNT_SCALE = 2.0
UNCLAMPED_FINAL_HIT_HEALTH_MULTIPLIER = 3.5

INFORMATIONAL_QUANTITY_GAPS: set[str] = set()
STATIC_MODEL_OMITTED_FACTORS = [
    "RUNTIME_BLUEPRINT_RIDER_ELIGIBILITY",
    "RUNTIME_OUTPUT_DAMAGE_HOOK",
    "BUFFS",
    "GENES",
    "MISSIONS",
    "SERVER_OR_MOD_HOOKS",
    "MOVEMENT",
    "STAMINA",
    "WEIGHT_AND_CARRY_REDUCTION",
    "AOE_AND_NODE_DENSITY",
    "MAP_AVAILABILITY",
    "AUTO_HARVEST",
    "COOLDOWN_OR_CHARGE",
    "EFFECTIVENESS_QUANTITY_MULTIPLIER_NOT_MODELED",
]
